#!/bin/sh
set -e
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d live-installer remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_icons/13.6ubuntu1
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/live-installer-progress-dot-off.png /usr/share/icons/live-installer-progress-dot-on.png
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'install-live-drivers.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'install-live-drivers.service' >/dev/null || true
		deb-systemd-helper unmask 'install-live-drivers.service' >/dev/null || true
	fi
fi
# End automatically added section
