#!/bin/bash
set -e

# Actualizar la caché de aplicaciones después de desinstalar
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -x "$(command -v update-desktop-database)" ]; then
        update-desktop-database -q
    fi
    
    if [ -x "$(command -v gtk-update-icon-cache)" ]; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    fi
fi

exit 0
